// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUfkFpX616LK8eHhUQt-xjAQSlKrTxXUM',
    appId: '1:500118427152:web:b1dcd81985775edf929c95',
    messagingSenderId: '500118427152',
    projectId: 'education-app-2dfed',
    authDomain: 'education-app-2dfed.firebaseapp.com',
    storageBucket: 'education-app-2dfed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0qIM0R0P4eXB_w13Y03e_OyqRp_OXAP0',
    appId: '1:500118427152:android:d00929ddc02d8a59929c95',
    messagingSenderId: '500118427152',
    projectId: 'education-app-2dfed',
    storageBucket: 'education-app-2dfed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6dMvmFGpXu2xx4D0Z-a1n24XfZ81LnV8',
    appId: '1:500118427152:ios:0886f24aa4cc088b929c95',
    messagingSenderId: '500118427152',
    projectId: 'education-app-2dfed',
    storageBucket: 'education-app-2dfed.appspot.com',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6dMvmFGpXu2xx4D0Z-a1n24XfZ81LnV8',
    appId: '1:500118427152:ios:9f0bc3ec80cbdad2929c95',
    messagingSenderId: '500118427152',
    projectId: 'education-app-2dfed',
    storageBucket: 'education-app-2dfed.appspot.com',
    iosBundleId: 'com.example.educationApp.RunnerTests',
  );
}
